In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("data_gempa_2020.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
dataset

Year  Month  Day      Time     Lat       Lon  Depth  Mag  \
0     2020     12   30  23:03:00  5.1231  125.2581   54.1  4.6   
1     2020     12   30  21:27:32  7.6359  126.9172   53.3  4.6   
2     2020     12   30  20:29:33 -6.6907  127.4441  393.4  4.5   
3     2020     12   30  19:36:05 -6.8738  147.6965   68.4  4.5   
4     2020     12   30  19:10:20 -2.3988  127.4859   16.4  4.8   
...    ...    ...  ...       ...     ...       ...    ...  ...   
4044  2020      1    1  12:28:34  0.1936  121.5572  141.3  4.1   
4045  2020      1    1  06:01:14 -6.7009  129.7667  155.1  4.4   
4046  2020      1    1  04:38:07  2.0047  126.7211   51.0  4.4   
4047  2020      1    1  00:35:48 -5.3373  152.6003   32.9  4.6   
4048  2020      1    1  00:28:20 -5.3245  152.5514   40.2  5.1   

                                          Region   Timestamp  
0             38 km SW of Sarangani, Philippines  1609369380  
1                40 km E of Baganga, Philippines  1609363652  
2            208 km NNE of Lospalos, Timor Leste  1609360173  
3     38 km SSW of Finschhafen, Papua New Guinea  1609356965  
4                 163 km NNW of Ambon, Indonesia  1609355420  
...                                          ...         ...  
4044                 38km S of Lemito, Indonesia  1577881714  
4045             219km NW of Saumlaki, Indonesia  1577858474  
4046              146km WNW of Tobelo, Indonesia  1577853487  
4047        107km SSW of Taron, Papua New Guinea  1577838948  
4048        108km SSW of Taron, Papua New Guinea  1577838500  

[4049 rows x 10 columns]

In [4]:
dataset.head()

Year  Month  Day      Time     Lat       Lon  Depth  Mag  \
0  2020     12   30  23:03:00  5.1231  125.2581   54.1  4.6   
1  2020     12   30  21:27:32  7.6359  126.9172   53.3  4.6   
2  2020     12   30  20:29:33 -6.6907  127.4441  393.4  4.5   
3  2020     12   30  19:36:05 -6.8738  147.6965   68.4  4.5   
4  2020     12   30  19:10:20 -2.3988  127.4859   16.4  4.8   

                                       Region   Timestamp  
0          38 km SW of Sarangani, Philippines  1609369380  
1             40 km E of Baganga, Philippines  1609363652  
2         208 km NNE of Lospalos, Timor Leste  1609360173  
3  38 km SSW of Finschhafen, Papua New Guinea  1609356965  
4              163 km NNW of Ambon, Indonesia  1609355420

In [5]:
# dnama = dataset['Region'].str.extract(' ([A-Za-z]+)\,', expand=False)
# dnama.value_counts()

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
print(X)

[[2020 12 30 ... 54.1 4.6 '38 km SW of Sarangani, Philippines']
 [2020 12 30 ... 53.3 4.6 '40 km E of Baganga, Philippines']
 [2020 12 30 ... 393.4 4.5 '208 km NNE of Lospalos, Timor Leste']
 ...
 [2020 1 1 ... 51.0 4.4 '146km WNW of Tobelo, Indonesia']
 [2020 1 1 ... 32.9 4.6 '107km SSW of Taron, Papua New Guinea']
 [2020 1 1 ... 40.2 5.1 '108km SSW of Taron, Papua New Guinea']]


In [8]:
print(y)

[1609369380 1609363652 1609360173 ... 1577853487 1577838948 1577838500]


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='constant')
imputer.fit(X[:, 1:9])
X[:, 1:9] = imputer.transform(X[:, 1:9])

In [10]:
print(X)

[[2020 12 30 ... 54.1 4.6 '38 km SW of Sarangani, Philippines']
 [2020 12 30 ... 53.3 4.6 '40 km E of Baganga, Philippines']
 [2020 12 30 ... 393.4 4.5 '208 km NNE of Lospalos, Timor Leste']
 ...
 [2020 1 1 ... 51.0 4.4 '146km WNW of Tobelo, Indonesia']
 [2020 1 1 ... 32.9 4.6 '107km SSW of Taron, Papua New Guinea']
 [2020 1 1 ... 40.2 5.1 '108km SSW of Taron, Papua New Guinea']]


In [11]:
print(X)

[[2020 12 30 ... 54.1 4.6 '38 km SW of Sarangani, Philippines']
 [2020 12 30 ... 53.3 4.6 '40 km E of Baganga, Philippines']
 [2020 12 30 ... 393.4 4.5 '208 km NNE of Lospalos, Timor Leste']
 ...
 [2020 1 1 ... 51.0 4.4 '146km WNW of Tobelo, Indonesia']
 [2020 1 1 ... 32.9 4.6 '107km SSW of Taron, Papua New Guinea']
 [2020 1 1 ... 40.2 5.1 '108km SSW of Taron, Papua New Guinea']]


In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [22]:
print(X)

[[1.0 12 30 ... 54.1 4.6 '38 km SW of Sarangani, Philippines']
 [1.0 12 30 ... 53.3 4.6 '40 km E of Baganga, Philippines']
 [1.0 12 30 ... 393.4 4.5 '208 km NNE of Lospalos, Timor Leste']
 ...
 [1.0 1 1 ... 51.0 4.4 '146km WNW of Tobelo, Indonesia']
 [1.0 1 1 ... 32.9 4.6 '107km SSW of Taron, Papua New Guinea']
 [1.0 1 1 ... 40.2 5.1 '108km SSW of Taron, Papua New Guinea']]


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1) 

In [16]:
print(X_train)

[[1.0 11 17 ... 10.0 5.1 '85 km E of Port-Olry, Vanuatu']
 [1.0 7 6 ... 133.7 4.5 'Maug Islands region, Northern Mariana Islands']
 [1.0 4 19 ... 10.0 4.2 '138 km SW of Panguna, Papua New Guinea']
 ...
 [1.0 1 7 ... 433.8 4.0 '51km SW of Agrihan, Northern Mariana Islands']
 [1.0 12 9 ... 10.0 4.6 '117 km SW of Merizo Village, Guam']
 [1.0 9 20 ... 10.0 5.3 '83 km E of Cortes, Philippines']]


In [17]:
print(X_test)

[[1.0 4 30 ... 10.0 4.4 '123 km ENE of Amahai, Indonesia']
 [1.0 4 19 ... 32.7 4.3 '187 km SSW of Abepura, Indonesia']
 [1.0 8 17 ... 10.0 5.3 '239 km NE of Samarai, Papua New Guinea']
 ...
 [1.0 1 22 ... 10.0 4.7 '260km SW of Merizo Village, Guam']
 [1.0 7 13 ... 10.0 4.9 '106 km S of Lakatoro, Vanuatu']
 [1.0 12 16 ... 74.6 4.8 '92 km SE of Pondaguitan, Philippines']]


In [18]:
print(y_train)

[3584 2142 1305 ...   68 3813 2987]


In [19]:
print(y_test)

[1428 1300 2600 1336 1328  739  964  785  876 1070 1792 3756 2959 2513
 2444 2816  715 3491 2318 2435 3925 2470 3252 1220  840 3461  520 2853
 2084 3225  281 2264  179 2950 3838 3080  280 1522 1010 3608  632  544
 3438 2115 1082 2552 2031  514   37  838  655 3052 2483 1310 3749 1403
 2049 2061 2905 1699 1732 1197 3474  306  341 1725 3818 2508 3116 3848
 1368 1986 2863 1582  304 3339 1590 2629 3530  494    9 1079 2306  354
 2498 2906 1017 1108 1058  482 1248  591  154 3386 1339 2185 2238 3488
 2675 2892 2350 1354 1069  830 3829 2923 1015 2391  392 1184  403  750
 3404  690 2885 3191 2704 2832 2198  459 3279 3954  353 1233  650 3562
 1808 3689 3550 3553 2984 2304 1030 3595  286  530  303  504  898 3093
 3946 1286  358 2946 2311 2706  508 1084 3912 1437  610  204 2908 2638
 1839 3561 2809 2098 3628 2496  631 1098 2216 3558 2649 3682   92 4047
 3244 3514 1572 2500 2540 1495 1982  841  136 3443 2591 3095  548 3256
 2163 2732 1056 3277  100 2968 3058 1634 2087 2673 3887  199 3412 2453
 1519 

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
print(y)

[4048 4047 4046 ...    2    1    0]


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [27]:
print(X_train)

[[1.0 11 17 ... 10.0 5.1 '85 km E of Port-Olry, Vanuatu']
 [1.0 7 6 ... 133.7 4.5 'Maug Islands region, Northern Mariana Islands']
 [1.0 4 19 ... 10.0 4.2 '138 km SW of Panguna, Papua New Guinea']
 ...
 [1.0 1 7 ... 433.8 4.0 '51km SW of Agrihan, Northern Mariana Islands']
 [1.0 12 9 ... 10.0 4.6 '117 km SW of Merizo Village, Guam']
 [1.0 9 20 ... 10.0 5.3 '83 km E of Cortes, Philippines']]


In [28]:
print(X_test)

[[1.0 4 30 ... 10.0 4.4 '123 km ENE of Amahai, Indonesia']
 [1.0 4 19 ... 32.7 4.3 '187 km SSW of Abepura, Indonesia']
 [1.0 8 17 ... 10.0 5.3 '239 km NE of Samarai, Papua New Guinea']
 ...
 [1.0 1 22 ... 10.0 4.7 '260km SW of Merizo Village, Guam']
 [1.0 7 13 ... 10.0 4.9 '106 km S of Lakatoro, Vanuatu']
 [1.0 12 16 ... 74.6 4.8 '92 km SE of Pondaguitan, Philippines']]


In [29]:
print(y_train)

[3584 2142 1305 ...   68 3813 2987]


In [30]:
print(y_test)

[1428 1300 2600 1336 1328  739  964  785  876 1070 1792 3756 2959 2513
 2444 2816  715 3491 2318 2435 3925 2470 3252 1220  840 3461  520 2853
 2084 3225  281 2264  179 2950 3838 3080  280 1522 1010 3608  632  544
 3438 2115 1082 2552 2031  514   37  838  655 3052 2483 1310 3749 1403
 2049 2061 2905 1699 1732 1197 3474  306  341 1725 3818 2508 3116 3848
 1368 1986 2863 1582  304 3339 1590 2629 3530  494    9 1079 2306  354
 2498 2906 1017 1108 1058  482 1248  591  154 3386 1339 2185 2238 3488
 2675 2892 2350 1354 1069  830 3829 2923 1015 2391  392 1184  403  750
 3404  690 2885 3191 2704 2832 2198  459 3279 3954  353 1233  650 3562
 1808 3689 3550 3553 2984 2304 1030 3595  286  530  303  504  898 3093
 3946 1286  358 2946 2311 2706  508 1084 3912 1437  610  204 2908 2638
 1839 3561 2809 2098 3628 2496  631 1098 2216 3558 2649 3682   92 4047
 3244 3514 1572 2500 2540 1495 1982  841  136 3443 2591 3095  548 3256
 2163 2732 1056 3277  100 2968 3058 1634 2087 2673 3887  199 3412 2453
 1519 